name: Manual Merge Remote Action
on: 
  workflow_dispatch:
    inputs:
    
      upstream:
        description: 'Upstream repository owner/name (e.g. discdiver/merge-from-upstream-repo)'
        required: true
        default: 'BerriAI/litellm'       # set the upstream repo
      upstream-branch:
        description: 'Upstream branch to merge from (e.g. main)'
        required: true
        default: 'main'           # set the upstream branch to merge from
      branch:
        #under ${{ github.repository }}"
        description: 'Branch to merge to'
        required: true
        default: 'main'         # set the branch to merge to
      useremail: 
        description: 'User email - required for git commits'
        required: false
      username:
        description: 'User name - required for git commits'
        required: false

jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail: "${{ github.pusher.email }}"
          #"${{ github.event.inputs.useremail}}"
          username: "${{ github.actor }}"
          #"${{ github.event.inputs.username}"
          upstream: ${{ github.event.inputs.upstream }}
          upstream-branch: ${{ github.event.inputs.upstream-branch }}
          branch: ${{ github.event.inputs.branch }}
          token: ${{ secrets.TOKEN }}
